# Generated by Django 5.2.6 on 2025-10-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=1, max_length=150, unique=True, verbose_name='Название тега'),
            preserve_default=False,
        ),
    ]
