version: '3.3'

volumes:
  pg_data:
  media_volume:
  backend_static_volume:
  frontend_static_volume:

services:
  db:
    container_name: foodgram-db
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    environment:
      - CSRF_TRUSTED_ORIGINS=https://foodgrammus.duckdns.org,http://foodgrammus.duckdns.org,http://89.169.162.168
    container_name: foodgram-backend
    image: mostloony/foodgram-backend
    env_file: .env
    volumes:
      - media_volume:/app/media/
      - backend_static_volume:/app/collected_static/
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    image: mostloony/foodgram-frontend
    command: ["sh", "-c", "cp -r /app/build/. /static/ && ls -la /static/"]
    volumes:
      - frontend_static_volume:/static/
    depends_on:
      - backend

  nginx:
    container_name: foodgram-proxy
    image: mostloony/foodgram-nginx
    ports:
      - "9001:80"
    volumes:
      - backend_static_volume:/app/collected_static/
      - frontend_static_volume:/static/
      - media_volume:/app/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend