server {
    listen 80;
    client_max_body_size 10M;


    location /media/ {
        alias /app/media/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
    }
    
    location /django_static/ {
        alias /app/collected_static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /auth/ {
        proxy_pass http://backend:8000/auth/;
        proxy_set_header Host $host;
    }

    location /admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $host;
    }

    location / {
        alias /static/;
        try_files $uri $uri/ /index.html;
    }
}
